# Generated by Django 3.2.6 on 2021-08-17 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='year_published',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator(message="Album year must be entered in the format: 'XXXX'.", regex='^\\d{4}$')]),
        ),
    ]
