# Generated by Django 3.2.6 on 2021-08-17 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210817_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='fav_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
